version: '3'

volumes:
  db:
  bundle:

services:
  db:
    image: postgres:12.4
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build: .
    command: bash -c "rm -f spec/dummy/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - ./node_modules:/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - TELEGRAM_CALLBACK_URL=https://d8aba999d57e.ngrok.io/telegram_chatbot/telegram
    stdin_open: true
    tty: true

  ngrok:
    image: wernight/ngrok
    ports:
      - 4040:4040
    environment:
      NGROK_PORT: 'web:3000'
